#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi


# Start everything in /etc/X11/xinit/xinitrc.d
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


# Setup Keyboard/Mouse Preferences
xset r rate 225 34
xset mouse 2/1 4
xset dpms 300 450 600
xset +dpms

# Enable two/three finger clicks
touchpad_name=xinput | grep Touchpad | awk '{ print $6 }' | awk -F '=' '{ print $2 }'
xinput set-prop $touchpad_name "libinput Click Method Enabled" 0 1

# Remap capslock to escape
setxkbmap -option caps:escape
# Turn on numlock
numlockx on

# Start Awesome WM
exec awesome

