# Export PATH
export PATH=/usr/local/bin:$PATH
export GOPATH="$HOME/projects/gocode"
export PATH=$PATH:$GOPATH/bin

# Source Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Use Nvim if Exists
if ! type "$nvim" > /dev/null; then
  alias vim="nvim"
fi

# Set Theme
autoload -Uz promptinit
promptinit
prompt paradox

### Aliases ###
# Shortcuts
alias proj='cd ~/projects'
alias sbox='source ~/.ssh/sbox.sh'
# Git
alias gc="git clone"
alias gs="git status"
alias gd="git diff"
alias ga="git add"
alias gi="git commit"
alias gh="git log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short"
alias ggo="git checkout"
alias gb="git branch"
alias gpom="git push origin master"
alias gprom='git pull --rebase origin master'

